ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [ com.happyrow.core.ApplicationKt.module ]
    }
}

application {
  sql {
    jdbcUrl = ${?DATABASE_URL}
    username = ${?DB_USERNAME}
    password = ${?DB_PASSWORD}
    maximumPoolSize = ${?DB_MAX_POOL_SIZE}
  }
  info {
    name = "happyrow-core"
    version = "1.0.0"
    environment = ${?ENVIRONMENT}
  }
}
